/**
 * Part of Windigo - Win32 API layer for Go
 * https://github.com/rodrigocfd/windigo
 * This library is released under the MIT license.
 */

package proc

import (
	"syscall"
)

var (
	user32Dll = syscall.NewLazyDLL("user32.dll")

	AdjustWindowRectEx            = user32Dll.NewProc("AdjustWindowRectEx")
	AllowSetForegroundWindow      = user32Dll.NewProc("AllowSetForegroundWindow")
	AppendMenu                    = user32Dll.NewProc("AppendMenuW")
	BeginDeferWindowPos           = user32Dll.NewProc("BeginDeferWindowPos")
	BeginPaint                    = user32Dll.NewProc("BeginPaint")
	CallNextHookEx                = user32Dll.NewProc("CallNextHookEx")
	CheckMenuItem                 = user32Dll.NewProc("CheckMenuItem")
	CheckMenuRadioItem            = user32Dll.NewProc("CheckMenuRadioItem")
	ClientToScreen                = user32Dll.NewProc("ClientToScreen")
	CopyAcceleratorTable          = user32Dll.NewProc("CopyAcceleratorTableW")
	CopyIcon                      = user32Dll.NewProc("CopyIcon")
	CreateAcceleratorTable        = user32Dll.NewProc("CreateAcceleratorTableW")
	CreateDialogParam             = user32Dll.NewProc("CreateDialogParamW")
	CreateMenu                    = user32Dll.NewProc("CreateMenu")
	CreatePopupMenu               = user32Dll.NewProc("CreatePopupMenu")
	CreateWindowEx                = user32Dll.NewProc("CreateWindowExW")
	DeferWindowPos                = user32Dll.NewProc("DeferWindowPos")
	DefWindowProc                 = user32Dll.NewProc("DefWindowProcW")
	DeleteMenu                    = user32Dll.NewProc("DeleteMenu")
	DestroyAcceleratorTable       = user32Dll.NewProc("DestroyAcceleratorTable")
	DestroyCaret                  = user32Dll.NewProc("DestroyCaret")
	DestroyCursor                 = user32Dll.NewProc("DestroyCursor")
	DestroyIcon                   = user32Dll.NewProc("DestroyIcon")
	DestroyMenu                   = user32Dll.NewProc("DestroyMenu")
	DestroyWindow                 = user32Dll.NewProc("DestroyWindow")
	DialogBoxParam                = user32Dll.NewProc("DialogBoxParamW")
	DispatchMessage               = user32Dll.NewProc("DispatchMessageW")
	DrawIcon                      = user32Dll.NewProc("DrawIcon")
	DrawMenuBar                   = user32Dll.NewProc("DrawMenuBar")
	EmptyClipboard                = user32Dll.NewProc("EmptyClipboard")
	EnableMenuItem                = user32Dll.NewProc("EnableMenuItem")
	EnableWindow                  = user32Dll.NewProc("EnableWindow")
	EndDeferWindowPos             = user32Dll.NewProc("EndDeferWindowPos")
	EndDialog                     = user32Dll.NewProc("EndDialog")
	EndMenu                       = user32Dll.NewProc("EndMenu")
	EndPaint                      = user32Dll.NewProc("EndPaint")
	EnumChildWindows              = user32Dll.NewProc("EnumChildWindows")
	EnumDisplayMonitors           = user32Dll.NewProc("EnumDisplayMonitors")
	EnumWindows                   = user32Dll.NewProc("EnumWindows")
	GetAncestor                   = user32Dll.NewProc("GetAncestor")
	GetAsyncKeyState              = user32Dll.NewProc("GetAsyncKeyState")
	GetCaretPos                   = user32Dll.NewProc("GetCaretPos")
	GetClassInfoEx                = user32Dll.NewProc("GetClassInfoExW")
	GetClientRect                 = user32Dll.NewProc("GetClientRect")
	GetCursorPos                  = user32Dll.NewProc("GetCursorPos")
	GetDC                         = user32Dll.NewProc("GetDC")
	GetDlgCtrlID                  = user32Dll.NewProc("GetDlgCtrlID")
	GetDlgItem                    = user32Dll.NewProc("GetDlgItem")
	GetDpiForSystem               = user32Dll.NewProc("GetDpiForSystem")
	GetDpiForWindow               = user32Dll.NewProc("GetDpiForWindow")
	GetFocus                      = user32Dll.NewProc("GetFocus")
	GetForegroundWindow           = user32Dll.NewProc("GetForegroundWindow")
	GetMenu                       = user32Dll.NewProc("GetMenu")
	GetMenuDefaultItem            = user32Dll.NewProc("GetMenuDefaultItem")
	GetMenuInfo                   = user32Dll.NewProc("GetMenuInfo")
	GetMenuItemCount              = user32Dll.NewProc("GetMenuItemCount")
	GetMenuItemID                 = user32Dll.NewProc("GetMenuItemID")
	GetMenuItemInfo               = user32Dll.NewProc("GetMenuItemInfoW")
	GetMessage                    = user32Dll.NewProc("GetMessageW")
	GetMonitorInfo                = user32Dll.NewProc("GetMonitorInfoW")
	GetNextDlgTabItem             = user32Dll.NewProc("GetNextDlgTabItem")
	GetParent                     = user32Dll.NewProc("GetParent")
	GetPhysicalCursorPos          = user32Dll.NewProc("GetPhysicalCursorPos")
	GetSubMenu                    = user32Dll.NewProc("GetSubMenu")
	GetSystemMenu                 = user32Dll.NewProc("GetSystemMenu")
	GetSystemMetrics              = user32Dll.NewProc("GetSystemMetrics")
	GetWindow                     = user32Dll.NewProc("GetWindow")
	GetWindowDC                   = user32Dll.NewProc("GetWindowDC")
	GetWindowLongPtr              = user32Dll.NewProc("GetWindowLongPtrW")
	GetWindowRect                 = user32Dll.NewProc("GetWindowRect")
	GetWindowText                 = user32Dll.NewProc("GetWindowTextW")
	GetWindowTextLength           = user32Dll.NewProc("GetWindowTextLengthW")
	HideCaret                     = user32Dll.NewProc("HideCaret")
	InsertMenu                    = user32Dll.NewProc("InsertMenuW")
	InsertMenuItem                = user32Dll.NewProc("InsertMenuItemW")
	InvalidateRect                = user32Dll.NewProc("InvalidateRect")
	IsChild                       = user32Dll.NewProc("IsChild")
	IsDialogMessage               = user32Dll.NewProc("IsDialogMessageW")
	IsDlgButtonChecked            = user32Dll.NewProc("IsDlgButtonChecked")
	IsGUIThread                   = user32Dll.NewProc("IsGUIThread")
	IsIconic                      = user32Dll.NewProc("IsIconic")
	IsWindow                      = user32Dll.NewProc("IsWindow")
	IsWindowEnabled               = user32Dll.NewProc("IsWindowEnabled")
	IsZoomed                      = user32Dll.NewProc("IsZoomed")
	KillTimer                     = user32Dll.NewProc("KillTimer")
	LoadAccelerators              = user32Dll.NewProc("LoadAcceleratorsW")
	LoadCursor                    = user32Dll.NewProc("LoadCursorW")
	LoadIcon                      = user32Dll.NewProc("LoadIconW")
	LoadImage                     = user32Dll.NewProc("LoadImageW")
	LoadMenu                      = user32Dll.NewProc("LoadMenuW")
	LockSetForegroundWindow       = user32Dll.NewProc("LockSetForegroundWindow")
	MenuItemFromPoint             = user32Dll.NewProc("MeunItemFromPoint")
	MessageBox                    = user32Dll.NewProc("MessageBoxW")
	MonitorFromPoint              = user32Dll.NewProc("MonitorFromPoint")
	MoveWindow                    = user32Dll.NewProc("MoveWindow")
	PostMessage                   = user32Dll.NewProc("PostMessageW")
	PostQuitMessage               = user32Dll.NewProc("PostQuitMessage")
	PostThreadMessage             = user32Dll.NewProc("PostThreadMessageW")
	RegisterClassEx               = user32Dll.NewProc("RegisterClassExW")
	RegisterWindowMessage         = user32Dll.NewProc("RegisterWindowMessageW")
	ReleaseDC                     = user32Dll.NewProc("ReleaseDC")
	ReplyMessage                  = user32Dll.NewProc("ReplyMessage")
	ScreenToClient                = user32Dll.NewProc("ScreenToClient")
	SendMessage                   = user32Dll.NewProc("SendMessageW")
	SetFocus                      = user32Dll.NewProc("SetFocus")
	SetForegroundWindow           = user32Dll.NewProc("SetForegroundWindow")
	SetMenuDefaultItem            = user32Dll.NewProc("SetMenuDefaultItem")
	SetMenuItemInfo               = user32Dll.NewProc("SetMenuItemInfoW")
	SetParent                     = user32Dll.NewProc("SetParent")
	SetProcessDPIAware            = user32Dll.NewProc("SetProcessDPIAware")
	SetProcessDpiAwarenessContext = user32Dll.NewProc("SetProcessDpiAwarenessContext")
	SetRect                       = user32Dll.NewProc("SetRect")
	SetTimer                      = user32Dll.NewProc("SetTimer")
	SetWindowLongPtr              = user32Dll.NewProc("SetWindowLongPtrW")
	SetWindowPos                  = user32Dll.NewProc("SetWindowPos")
	SetWindowsHookEx              = user32Dll.NewProc("SetWindowsHookExW")
	SetWindowText                 = user32Dll.NewProc("SetWindowTextW")
	ShowCaret                     = user32Dll.NewProc("ShowCaret")
	ShowWindow                    = user32Dll.NewProc("ShowWindow")
	SystemParametersInfo          = user32Dll.NewProc("SystemParametersInfoW")
	TrackPopupMenu                = user32Dll.NewProc("TrackPopupMenu")
	TranslateAccelerator          = user32Dll.NewProc("TranslateAcceleratorW")
	TranslateMessage              = user32Dll.NewProc("TranslateMessage")
	UnhookWindowsHookEx           = user32Dll.NewProc("UnhookWindowsHookEx")
	UpdateWindow                  = user32Dll.NewProc("UpdateWindow")
)
