/**
 * Part of Wingows - Win32 API layer for Go
 * https://github.com/rodrigocfd/wingows
 * This library is released under the MIT license.
 */

package gui

import (
	"fmt"
	"unsafe"
	"wingows/co"
	"wingows/win"
)

type _WindowSetupBase struct {
	wasInit bool

	classNameBuf     []uint16
	ClassName        string      // Optional, defaults to a hash generated by WNDCLASSEX parameters. Passed to RegisterClassEx.
	ClassStyle       co.CS       // Window class style, passed to RegisterClassEx.
	HCursor          win.HCURSOR // Window cursor, passed to RegisterClassEx.
	HBrushBackground win.HBRUSH  // Window background brush, passed to RegisterClassEx.

	Style   co.WS    // Window style, passed to CreateWindowEx.
	ExStyle co.WS_EX // Window extended style, passed to CreateWindowEx. For a border, use WS_EX_CLIENTEDGE
}

func (me *_WindowSetupBase) genWndclassex(
	hInst win.HINSTANCE,
	defBgColor co.COLOR,
	additionalInits func(wcx *win.WNDCLASSEX)) *win.WNDCLASSEX {

	wcx := win.WNDCLASSEX{}

	wcx.CbSize = uint32(unsafe.Sizeof(wcx))
	wcx.HInstance = hInst
	wcx.Style = me.ClassStyle

	if me.HCursor != 0 { // user specified a cursor
		wcx.HCursor = me.HCursor
	} else {
		wcx.HCursor = win.HINSTANCE(0).LoadCursor(co.IDC_ARROW)
	}

	if me.HBrushBackground != 0 { // user specified a background brush
		wcx.HbrBackground = me.HBrushBackground
	} else {
		wcx.HbrBackground = win.CreateSysColorBrush(defBgColor)
	}

	if additionalInits != nil {
		additionalInits(&wcx)
	}

	// After all the fields are set, if user didn't choose a class name, we
	// generate one by hashing all the WNDCLASSEX fields. That's why it must be
	// the last thing to be done.
	if me.ClassName == "" {
		me.ClassName = fmt.Sprintf("%x.%x.%x.%x.%x.%x.%x.%x.%x.%x",
			wcx.Style, wcx.LpfnWndProc, wcx.CbClsExtra, wcx.CbWndExtra,
			wcx.HInstance, wcx.HIcon, wcx.HCursor, wcx.HbrBackground,
			wcx.LpszMenuName, wcx.HIconSm)
	}

	me.classNameBuf = win.StrToSlice(me.ClassName) // keep the buffer, we'll use a pointer to it
	wcx.LpszClassName = uintptr(unsafe.Pointer(&me.classNameBuf[0]))

	return &wcx
}

//------------------------------------------------------------------------------

// Setup parameters for WindowMain.
type _WindowSetupMain struct {
	_WindowSetupBase

	HIcon      win.HICON // Icon associated with the window, passed to RegisterClassEx.
	HIconSmall win.HICON // Small icon associated with the window, passed to RegisterClassEx.

	Title    string // The title of the window, passed to CreateWindowEx.
	Width    uint32 // Initial width of the window, passed to CreateWindowEx.
	Height   uint32 // Initial height of the window, passed to CreateWindowEx.
	MainMenu Menu   // Main window menu, passed to CreateWindowEx.

	AcceleratorTable AccelTable // Accelerator table used in main loop. Will be automatically destroyed.
	CmdShow          co.SW      // Passed to ShowWindow, defaults to SW_SHOW.
}

func (me *_WindowSetupMain) initOnce() {
	if !me.wasInit {
		me.wasInit = true

		me.ClassStyle = co.CS_DBLCLKS

		me.Width = 600 // arbitrary dimensions
		me.Height = 500
		me.Style = co.WS_CAPTION | co.WS_SYSMENU | co.WS_CLIPCHILDREN | co.WS_BORDER
		me.ExStyle = co.WS_EX_NONE

		me.CmdShow = co.SW_SHOW
	}
}

func (me *_WindowSetupMain) genWndclassex(hInst win.HINSTANCE) *win.WNDCLASSEX {
	return me._WindowSetupBase.genWndclassex(hInst, co.COLOR_BTNFACE,
		func(wcx *win.WNDCLASSEX) {
			wcx.HIcon = me.HIcon
			wcx.HIconSm = me.HIconSmall
		})
}

//------------------------------------------------------------------------------

// Setup parameters for WindowModal.
type _WindowSetupModal struct {
	_WindowSetupBase

	Title  string // The title of the window, passed to CreateWindowEx.
	Width  uint32 // Initial width of the window, passed to CreateWindowEx.
	Height uint32 // Initial height of the window, passed to CreateWindowEx.
}

func (me *_WindowSetupModal) initOnce() {
	if !me.wasInit {
		me.wasInit = true

		me.ClassStyle = co.CS_DBLCLKS

		me.Width = 500 // arbitrary dimensions
		me.Height = 400
		me.Style = co.WS_CAPTION | co.WS_SYSMENU | co.WS_CLIPCHILDREN | co.WS_BORDER | co.WS_VISIBLE
		me.ExStyle = co.WS_EX_NONE
	}
}

func (me *_WindowSetupModal) genWndclassex(hInst win.HINSTANCE) *win.WNDCLASSEX {
	return me._WindowSetupBase.genWndclassex(hInst, co.COLOR_BTNFACE, nil)
}

//------------------------------------------------------------------------------

// Setup parameters for WindowControl.
type _WindowSetupControl struct {
	_WindowSetupBase
}

func (me *_WindowSetupControl) initOnce() {
	if !me.wasInit {
		me.wasInit = true

		me.ClassStyle = co.CS_DBLCLKS

		me.Style = co.WS_CHILD | co.WS_VISIBLE | co.WS_CLIPCHILDREN | co.WS_CLIPSIBLINGS
		me.ExStyle = co.WS_EX_NONE
	}
}

func (me *_WindowSetupControl) genWndclassex(hInst win.HINSTANCE) *win.WNDCLASSEX {
	return me._WindowSetupBase.genWndclassex(hInst, co.COLOR_WINDOW, nil)
}
