/**
 * Part of Windigo - Win32 API layer for Go
 * https://github.com/rodrigocfd/windigo
 * This library is released under the MIT license.
 */

package co

// ComboBox messages.
type CB WM

const (
	CB_GETEDITSEL            CB = 0x0140
	CB_LIMITTEXT             CB = 0x0141
	CB_SETEDITSEL            CB = 0x0142
	CB_ADDSTRING             CB = 0x0143
	CB_DELETESTRING          CB = 0x0144
	CB_DIR                   CB = 0x0145
	CB_GETCOUNT              CB = 0x0146
	CB_GETCURSEL             CB = 0x0147
	CB_GETLBTEXT             CB = 0x0148
	CB_GETLBTEXTLEN          CB = 0x0149
	CB_INSERTSTRING          CB = 0x014a
	CB_RESETCONTENT          CB = 0x014b
	CB_FINDSTRING            CB = 0x014c
	CB_SELECTSTRING          CB = 0x014d
	CB_SETCURSEL             CB = 0x014e
	CB_SHOWDROPDOWN          CB = 0x014f
	CB_GETITEMDATA           CB = 0x0150
	CB_SETITEMDATA           CB = 0x0151
	CB_GETDROPPEDCONTROLRECT CB = 0x0152
	CB_SETITEMHEIGHT         CB = 0x0153
	CB_GETITEMHEIGHT         CB = 0x0154
	CB_SETEXTENDEDUI         CB = 0x0155
	CB_GETEXTENDEDUI         CB = 0x0156
	CB_GETDROPPEDSTATE       CB = 0x0157
	CB_FINDSTRINGEXACT       CB = 0x0158
	CB_SETLOCALE             CB = 0x0159
	CB_GETLOCALE             CB = 0x015a
	CB_GETTOPINDEX           CB = 0x015b
	CB_SETTOPINDEX           CB = 0x015c
	CB_GETHORIZONTALEXTENT   CB = 0x015d
	CB_SETHORIZONTALEXTENT   CB = 0x015e
	CB_GETDROPPEDWIDTH       CB = 0x015f
	CB_SETDROPPEDWIDTH       CB = 0x0160
	CB_INITSTORAGE           CB = 0x0161
	CB_GETCOMBOBOXINFO       CB = 0x0164
	CB_MSGMAX                CB = 0x0165
)

// COMBOBOXEXITEM mask.
type CBEIF uint32

const (
	CBEIF_TEXT          CBEIF = 0x00000001
	CBEIF_IMAGE         CBEIF = 0x00000002
	CBEIF_SELECTEDIMAGE CBEIF = 0x00000004
	CBEIF_OVERLAY       CBEIF = 0x00000008
	CBEIF_INDENT        CBEIF = 0x00000010
	CBEIF_LPARAM        CBEIF = 0x00000020
	CBEIF_DI_SETITEM    CBEIF = 0x10000000
)

// ComboBoxEx messages.
type CBEM WM

const (
	CBEM_DELETEITEM       CBEM = CBEM(CB_DELETESTRING)
	CBEM_SETUNICODEFORMAT CBEM = CBEM(CCM_SETUNICODEFORMAT)
	CBEM_GETUNICODEFORMAT CBEM = CBEM(CCM_GETUNICODEFORMAT)
	CBEM_SETWINDOWTHEME   CBEM = CBEM(CCM_SETWINDOWTHEME)
	CBEM_SETIMAGELIST     CBEM = CBEM(WM_USER + 2)
	CBEM_GETIMAGELIST     CBEM = CBEM(WM_USER + 3)
	CBEM_GETCOMBOCONTROL  CBEM = CBEM(WM_USER + 6)
	CBEM_GETEDITCONTROL   CBEM = CBEM(WM_USER + 7)
	CBEM_GETEXTENDEDSTYLE CBEM = CBEM(WM_USER + 9)
	CBEM_HASEDITCHANGED   CBEM = CBEM(WM_USER + 10)
	CBEM_INSERTITEM       CBEM = CBEM(WM_USER + 11)
	CBEM_SETITEM          CBEM = CBEM(WM_USER + 12)
	CBEM_GETITEM          CBEM = CBEM(WM_USER + 13)
	CBEM_SETEXTENDEDSTYLE CBEM = CBEM(WM_USER + 14)
)

// ComboBoxEx notifications, sent via WM_NOTIFY.
type CBEN NM

const (
	_CBEN_FIRST CBEN = -800

	CBEN_INSERTITEM  CBEN = _CBEN_FIRST - 1
	CBEN_DELETEITEM  CBEN = _CBEN_FIRST - 2
	CBEN_BEGINEDIT   CBEN = _CBEN_FIRST - 4
	CBEN_ENDEDIT     CBEN = _CBEN_FIRST - 6
	CBEN_GETDISPINFO CBEN = _CBEN_FIRST - 7
	CBEN_DRAGBEGIN   CBEN = _CBEN_FIRST - 9
)

// NMCBEENDEDIT iWhy.
type CBENF int32

const (
	CBENF_KILLFOCUS CBENF = 1
	CBENF_RETURN    CBENF = 2
	CBENF_ESCAPE    CBENF = 3
	CBENF_DROPDOWN  CBENF = 4
)

// ComboBox notifications, sent via WM_COMMAND.
type CBN int32

const (
	CBN_ERRSPACE     CBN = -1
	CBN_SELCHANGE    CBN = 1
	CBN_DBLCLK       CBN = 2
	CBN_SETFOCUS     CBN = 3
	CBN_KILLFOCUS    CBN = 4
	CBN_EDITCHANGE   CBN = 5
	CBN_EDITUPDATE   CBN = 6
	CBN_DROPDOWN     CBN = 7
	CBN_CLOSEUP      CBN = 8
	CBN_SELENDOK     CBN = 9
	CBN_SELENDCANCEL CBN = 10
)

// ComboBox styles.
type CBS WS

const (
	CBS_SIMPLE            CBS = 0x0001
	CBS_DROPDOWN          CBS = 0x0002
	CBS_DROPDOWNLIST      CBS = 0x0003
	CBS_OWNERDRAWFIXED    CBS = 0x0010
	CBS_OWNERDRAWVARIABLE CBS = 0x0020
	CBS_AUTOHSCROLL       CBS = 0x0040
	CBS_OEMCONVERT        CBS = 0x0080
	CBS_SORT              CBS = 0x0100
	CBS_HASSTRINGS        CBS = 0x0200
	CBS_NOINTEGRALHEIGHT  CBS = 0x0400
	CBS_DISABLENOSCROLL   CBS = 0x0800
	CBS_UPPERCASE         CBS = 0x2000
	CBS_LOWERCASE         CBS = 0x4000
)

// Common controls shared messages.
type CCM WM

const (
	_CCM_FIRST CCM = 0x2000

	CCM_SETBKCOLOR       CCM = _CCM_FIRST + 1
	CCM_SETCOLORSCHEME   CCM = _CCM_FIRST + 2
	CCM_GETCOLORSCHEME   CCM = _CCM_FIRST + 3
	CCM_GETDROPTARGET    CCM = _CCM_FIRST + 4
	CCM_SETUNICODEFORMAT CCM = _CCM_FIRST + 5
	CCM_GETUNICODEFORMAT CCM = _CCM_FIRST + 6
	CCM_SETVERSION       CCM = _CCM_FIRST + 0x7
	CCM_GETVERSION       CCM = _CCM_FIRST + 0x8
	CCM_SETNOTIFYWINDOW  CCM = _CCM_FIRST + 0x9
	CCM_SETWINDOWTHEME   CCM = _CCM_FIRST + 0xb
	CCM_DPISCALE         CCM = _CCM_FIRST + 0xc
)

// NMCUSTOMDRAW uItemState.
type CDIS uint32

const (
	CDIS_SELECTED         CDIS = 0x0001
	CDIS_GRAYED           CDIS = 0x0002
	CDIS_DISABLED         CDIS = 0x0004
	CDIS_CHECKED          CDIS = 0x0008
	CDIS_FOCUS            CDIS = 0x0010
	CDIS_DEFAULT          CDIS = 0x0020
	CDIS_HOT              CDIS = 0x0040
	CDIS_MARKED           CDIS = 0x0080
	CDIS_INDETERMINATE    CDIS = 0x0100
	CDIS_SHOWKEYBOARDCUES CDIS = 0x0200
	CDIS_NEARHOT          CDIS = 0x0400
	CDIS_OTHERSIDEHOT     CDIS = 0x0800
	CDIS_DROPHILITED      CDIS = 0x1000
)

// NMCUSTOMDRAW dwDrawStage.
type CDDS uint32

const (
	CDDS_PREPAINT      CDDS = 0x00000001
	CDDS_POSTPAINT     CDDS = 0x00000002
	CDDS_PREERASE      CDDS = 0x00000003
	CDDS_POSTERASE     CDDS = 0x00000004
	CDDS_ITEM          CDDS = 0x00010000
	CDDS_ITEMPREPAINT  CDDS = CDDS_ITEM | CDDS_PREPAINT
	CDDS_ITEMPOSTPAINT CDDS = CDDS_ITEM | CDDS_POSTPAINT
	CDDS_ITEMPREERASE  CDDS = CDDS_ITEM | CDDS_PREERASE
	CDDS_ITEMPOSTERASE CDDS = CDDS_ITEM | CDDS_POSTERASE
	CDDS_SUBITEM       CDDS = 0x00020000
)

// NM_CUSTOMDRAW return value.
type CDRF uint32

const (
	CDRF_DODEFAULT         CDRF = 0x00000000
	CDRF_NEWFONT           CDRF = 0x00000002
	CDRF_SKIPDEFAULT       CDRF = 0x00000004
	CDRF_DOERASE           CDRF = 0x00000008
	CDRF_SKIPPOSTPAINT     CDRF = 0x00000100
	CDRF_NOTIFYPOSTPAINT   CDRF = 0x00000010
	CDRF_NOTIFYITEMDRAW    CDRF = 0x00000020
	CDRF_NOTIFYSUBITEMDRAW CDRF = 0x00000020
	CDRF_NOTIFYPOSTERASE   CDRF = 0x00000040
)

// Clipboard formats.
type CF uint16

const (
	CF_TEXT            CF = 1
	CF_BITMAP          CF = 2
	CF_METAFILEPICT    CF = 3
	CF_SYLK            CF = 4
	CF_DIF             CF = 5
	CF_TIFF            CF = 6
	CF_OEMTEXT         CF = 7
	CF_DIB             CF = 8
	CF_PALETTE         CF = 9
	CF_PENDATA         CF = 10
	CF_RIFF            CF = 11
	CF_WAVE            CF = 12
	CF_UNICODETEXT     CF = 13
	CF_ENHMETAFILE     CF = 14
	CF_HDROP           CF = 15
	CF_LOCALE          CF = 16
	CF_DIBV5           CF = 17
	CF_MAX             CF = 18
	CF_OWNERDISPLAY    CF = 0x0080
	CF_DSPTEXT         CF = 0x0081
	CF_DSPBITMAP       CF = 0x0082
	CF_DSPMETAFILEPICT CF = 0x0083
	CF_DSPENHMETAFILE  CF = 0x008e
	CF_PRIVATEFIRST    CF = 0x0200
	CF_PRIVATELAST     CF = 0x02ff
	CF_GDIOBJFIRST     CF = 0x0300
	CF_GDIOBJLAST      CF = 0x03ff
)

// CoCreateInstance() dwClsContext.
type CLSCTX uint32

const (
	CLSCTX_INPROC_SERVER          CLSCTX = 0x1
	CLSCTX_INPROC_HANDLER         CLSCTX = 0x2
	CLSCTX_LOCAL_SERVER           CLSCTX = 0x4
	CLSCTX_INPROC_SERVER16        CLSCTX = 0x8
	CLSCTX_REMOTE_SERVER          CLSCTX = 0x10
	CLSCTX_INPROC_HANDLER16       CLSCTX = 0x20
	CLSCTX_NO_CODE_DOWNLOAD       CLSCTX = 0x400
	CLSCTX_NO_CUSTOM_MARSHAL      CLSCTX = 0x1000
	CLSCTX_ENABLE_CODE_DOWNLOAD   CLSCTX = 0x2000
	CLSCTX_NO_FAILURE_LOG         CLSCTX = 0x4000
	CLSCTX_DISABLE_AAA            CLSCTX = 0x8000
	CLSCTX_ENABLE_AAA             CLSCTX = 0x10000
	CLSCTX_FROM_DEFAULT_CONTEXT   CLSCTX = 0x20000
	CLSCTX_ACTIVATE_X86_SERVER    CLSCTX = 0x40000
	CLSCTX_ACTIVATE_32_BIT_SERVER CLSCTX = CLSCTX_ACTIVATE_X86_SERVER
	CLSCTX_ACTIVATE_64_BIT_SERVER CLSCTX = 0x80000
	CLSCTX_ENABLE_CLOAKING        CLSCTX = 0x100000
	CLSCTX_APPCONTAINER           CLSCTX = 0x400000
	CLSCTX_ACTIVATE_AAA_AS_IU     CLSCTX = 0x800000
	CLSCTX_ACTIVATE_ARM32_SERVER  CLSCTX = 0x2000000
	CLSCTX_PS_DLL                 CLSCTX = 0x80000000
	CLSCTX_ALL                    CLSCTX = CLSCTX_INPROC_SERVER | CLSCTX_INPROC_HANDLER | CLSCTX_LOCAL_SERVER | CLSCTX_REMOTE_SERVER
	CLSCTX_SERVER                 CLSCTX = CLSCTX_INPROC_SERVER | CLSCTX_LOCAL_SERVER | CLSCTX_REMOTE_SERVER
)

// CoInitializeEx() dwCoInit.
type COINIT uint32

const (
	COINIT_APARTMENTTHREADED COINIT = 0x2
	COINIT_MULTITHREADED     COINIT = 0x0
	COINIT_DISABLE_OLE1DDE   COINIT = 0x4
	COINIT_SPEED_OVER_MEMORY COINIT = 0x8
)

// System colors.
type COLOR uint32

const (
	COLOR_SCROLLBAR               COLOR = 0
	COLOR_BACKGROUND              COLOR = 1
	COLOR_ACTIVECAPTION           COLOR = 2
	COLOR_INACTIVECAPTION         COLOR = 3
	COLOR_MENU                    COLOR = 4
	COLOR_WINDOW                  COLOR = 5
	COLOR_WINDOWFRAME             COLOR = 6
	COLOR_MENUTEXT                COLOR = 7
	COLOR_WINDOWTEXT              COLOR = 8
	COLOR_CAPTIONTEXT             COLOR = 9
	COLOR_ACTIVEBORDER            COLOR = 10
	COLOR_INACTIVEBORDER          COLOR = 11
	COLOR_APPWORKSPACE            COLOR = 12
	COLOR_HIGHLIGHT               COLOR = 13
	COLOR_HIGHLIGHTTEXT           COLOR = 14
	COLOR_BTNFACE                 COLOR = 15
	COLOR_BTNSHADOW               COLOR = 16
	COLOR_GRAYTEXT                COLOR = 17
	COLOR_BTNTEXT                 COLOR = 18
	COLOR_INACTIVECAPTIONTEXT     COLOR = 19
	COLOR_BTNHIGHLIGHT            COLOR = 20
	COLOR_3DDKSHADOW              COLOR = 21
	COLOR_3DLIGHT                 COLOR = 22
	COLOR_INFOTEXT                COLOR = 23
	COLOR_INFOBK                  COLOR = 24
	COLOR_HOTLIGHT                COLOR = 26
	COLOR_GRADIENTACTIVECAPTION   COLOR = 27
	COLOR_GRADIENTINACTIVECAPTION COLOR = 28
	COLOR_MENUHILIGHT             COLOR = 29
	COLOR_MENUBAR                 COLOR = 30
	COLOR_DESKTOP                 COLOR = COLOR_BACKGROUND
	COLOR_3DFACE                  COLOR = COLOR_BTNFACE
	COLOR_3DSHADOW                COLOR = COLOR_BTNSHADOW
	COLOR_3DHIGHLIGHT             COLOR = COLOR_BTNHIGHLIGHT
	COLOR_3DHILIGHT               COLOR = COLOR_BTNHIGHLIGHT
	COLOR_BTNHILIGHT              COLOR = COLOR_BTNHIGHLIGHT
)

// Window class styles.
type CS uint32

const (
	CS_VREDRAW         CS = 0x0001
	CS_HREDRAW         CS = 0x0002
	CS_DBLCLKS         CS = 0x0008
	CS_OWNDC           CS = 0x0020
	CS_CLASSDC         CS = 0x0040
	CS_PARENTDC        CS = 0x0080
	CS_NOCLOSE         CS = 0x0200
	CS_SAVEBITS        CS = 0x0800
	CS_BYTEALIGNCLIENT CS = 0x1000
	CS_BYTEALIGNWINDOW CS = 0x2000
	CS_GLOBALCLASS     CS = 0x4000
	CS_IME             CS = 0x00010000
	CS_DROPSHADOW      CS = 0x00020000
)

// WM_GETDLGCODE return value.
type DLGC uint32

const (
	DLGC_WANTARROWS      DLGC = 0x0001 // Control wants arrow keys
	DLGC_WANTTAB         DLGC = 0x0002 // Control wants tab keys
	DLGC_WANTALLKEYS     DLGC = 0x0004 // Control wants all keys
	DLGC_WANTMESSAGE     DLGC = 0x0004 // Pass message to control
	DLGC_HASSETSEL       DLGC = 0x0008 // Understands EM_SETSEL message
	DLGC_DEFPUSHBUTTON   DLGC = 0x0010 // Default pushbutton
	DLGC_UNDEFPUSHBUTTON DLGC = 0x0020 // Non-default pushbutton
	DLGC_RADIOBUTTON     DLGC = 0x0040 // Radio button
	DLGC_WANTCHARS       DLGC = 0x0080 // Want WM_CHAR messages
	DLGC_STATIC          DLGC = 0x0100 // Static item: don't include
	DLGC_BUTTON          DLGC = 0x2000 // Button item: can be checked
)

// SetProcessDpiAwarenessContext() value.
type DPI_AWARE_CTX int32

const (
	DPI_AWARE_CTX_UNAWARE           DPI_AWARE_CTX = -1
	DPI_AWARE_CTX_SYSTEM_AWARE      DPI_AWARE_CTX = -2
	DPI_AWARE_CTX_PER_MON_AWARE     DPI_AWARE_CTX = -3
	DPI_AWARE_CTX_PER_MON_AWARE_V2  DPI_AWARE_CTX = -4
	DPI_AWARE_CTX_UNAWARE_GDISCALED DPI_AWARE_CTX = -5
)

// Composes SFGAO.
type DROPEFFECT uint32

const (
	DROPEFFECT_NONE   DROPEFFECT = 0
	DROPEFFECT_COPY   DROPEFFECT = 1
	DROPEFFECT_MOVE   DROPEFFECT = 2
	DROPEFFECT_LINK   DROPEFFECT = 4
	DROPEFFECT_SCROLL DROPEFFECT = 0x80000000
)

// DateTimePicker messages.
type DTM WM

const (
	_DTM_FIRST DTM = 0x1000

	DTM_GETSYSTEMTIME         DTM = _DTM_FIRST + 1
	DTM_SETSYSTEMTIME         DTM = _DTM_FIRST + 2
	DTM_GETRANGE              DTM = _DTM_FIRST + 3
	DTM_SETRANGE              DTM = _DTM_FIRST + 4
	DTM_SETFORMAT             DTM = _DTM_FIRST + 50
	DTM_SETMCCOLOR            DTM = _DTM_FIRST + 6
	DTM_GETMCCOLOR            DTM = _DTM_FIRST + 7
	DTM_GETMONTHCAL           DTM = _DTM_FIRST + 8
	DTM_SETMCFONT             DTM = _DTM_FIRST + 9
	DTM_GETMCFONT             DTM = _DTM_FIRST + 10
	DTM_SETMCSTYLE            DTM = _DTM_FIRST + 11
	DTM_GETMCSTYLE            DTM = _DTM_FIRST + 12
	DTM_CLOSEMONTHCAL         DTM = _DTM_FIRST + 13
	DTM_GETDATETIMEPICKERINFO DTM = _DTM_FIRST + 14
	DTM_GETIDEALSIZE          DTM = _DTM_FIRST + 15
)

// DateTimePicker notifications, sent via WM_NOTIFY.
type DTN NM

const (
	_DTN_FIRST  DTN = -740
	_DTN_FIRST2 DTN = -753

	DTN_CLOSEUP        DTN = _DTN_FIRST2 - 0
	DTN_DROPDOWN       DTN = _DTN_FIRST2 - 1
	DTN_DATETIMECHANGE DTN = _DTN_FIRST2 - 6
	DTN_FORMATQUERY    DTN = _DTN_FIRST - 2
	DTN_FORMAT         DTN = _DTN_FIRST - 3
	DTN_WMKEYDOWN      DTN = _DTN_FIRST - 4
	DTN_USERSTRING     DTN = _DTN_FIRST - 5
)

// DateTimePicker styles.
type DTS WS

const (
	DTS_UPDOWN                 DTS = 0x0001
	DTS_SHOWNONE               DTS = 0x0002
	DTS_SHORTDATEFORMAT        DTS = 0x0000
	DTS_LONGDATEFORMAT         DTS = 0x0004
	DTS_SHORTDATECENTURYFORMAT DTS = 0x000c
	DTS_TIMEFORMAT             DTS = 0x0009
	DTS_APPCANPARSE            DTS = 0x0010
	DTS_RIGHTALIGN             DTS = 0x0020
)
