/**
 * Part of Wingows - Win32 API layer for Go
 * https://github.com/rodrigocfd/wingows
 * This library is released under the MIT license.
 */

package co

type DPI_AWARE_CTX int32 // SetProcessDpiAwarenessContext

const (
	DPI_AWARE_CTX_UNAWARE           DPI_AWARE_CTX = -1
	DPI_AWARE_CTX_SYSTEM_AWARE      DPI_AWARE_CTX = -2
	DPI_AWARE_CTX_PER_MON_AWARE     DPI_AWARE_CTX = -3
	DPI_AWARE_CTX_PER_MON_AWARE_V2  DPI_AWARE_CTX = -4
	DPI_AWARE_CTX_UNAWARE_GDISCALED DPI_AWARE_CTX = -5
)

type EM WM // edit control message

const (
	EM_GETSEL              EM = 0x00B0
	EM_SETSEL              EM = 0x00B1
	EM_GETRECT             EM = 0x00B2
	EM_SETRECT             EM = 0x00B3
	EM_SETRECTNP           EM = 0x00B4
	EM_SCROLL              EM = 0x00B5
	EM_LINESCROLL          EM = 0x00B6
	EM_SCROLLCARET         EM = 0x00B7
	EM_GETMODIFY           EM = 0x00B8
	EM_SETMODIFY           EM = 0x00B9
	EM_GETLINECOUNT        EM = 0x00BA
	EM_LINEINDEX           EM = 0x00BB
	EM_SETHANDLE           EM = 0x00BC
	EM_GETHANDLE           EM = 0x00BD
	EM_GETTHUMB            EM = 0x00BE
	EM_LINELENGTH          EM = 0x00C1
	EM_REPLACESEL          EM = 0x00C2
	EM_GETLINE             EM = 0x00C4
	EM_LIMITTEXT           EM = 0x00C5
	EM_CANUNDO             EM = 0x00C6
	EM_UNDO                EM = 0x00C7
	EM_FMTLINES            EM = 0x00C8
	EM_LINEFROMCHAR        EM = 0x00C9
	EM_SETTABSTOPS         EM = 0x00CB
	EM_SETPASSWORDCHAR     EM = 0x00CC
	EM_EMPTYUNDOBUFFER     EM = 0x00CD
	EM_GETFIRSTVISIBLELINE EM = 0x00CE
	EM_SETREADONLY         EM = 0x00CF
	EM_SETWORDBREAKPROC    EM = 0x00D0
	EM_GETWORDBREAKPROC    EM = 0x00D1
	EM_GETPASSWORDCHAR     EM = 0x00D2
	EM_SETMARGINS          EM = 0x00D3
	EM_GETMARGINS          EM = 0x00D4
	EM_SETLIMITTEXT        EM = EM_LIMITTEXT
	EM_GETLIMITTEXT        EM = 0x00D5
	EM_POSFROMCHAR         EM = 0x00D6
	EM_CHARFROMPOS         EM = 0x00D7
	EM_SETIMESTATUS        EM = 0x00D8
	EM_GETIMESTATUS        EM = 0x00D9
)

type EMF uint32 // NMLVEMPTYMARKUP

const (
	EMF_NULL     EMF = 0x00000000
	EMF_CENTERED EMF = 0x00000001
)

type ES WS // edit control style

const (
	ES_LEFT        ES = 0x0000
	ES_CENTER      ES = 0x0001
	ES_RIGHT       ES = 0x0002
	ES_MULTILINE   ES = 0x0004
	ES_UPPERCASE   ES = 0x0008
	ES_LOWERCASE   ES = 0x0010
	ES_PASSWORD    ES = 0x0020
	ES_AUTOVSCROLL ES = 0x0040
	ES_AUTOHSCROLL ES = 0x0080
	ES_NOHIDESEL   ES = 0x0100
	ES_OEMCONVERT  ES = 0x0400
	ES_READONLY    ES = 0x0800
	ES_WANTRETURN  ES = 0x1000
	ES_NUMBER      ES = 0x2000
)

type ERROR uint32 // GetLastError

const (
	ERROR_SUCCESS              ERROR = 0
	ERROR_INVALID_HANDLE       ERROR = 6
	ERROR_SHARING_VIOLATION    ERROR = 32
	ERROR_CLASS_ALREADY_EXISTS ERROR = 1410
)

type FAPPCOMMAND uint32 // WM_APPCOMMAND

const (
	FAPPCOMMAND_MOUSE FAPPCOMMAND = 0x8000
	FAPPCOMMAND_KEY   FAPPCOMMAND = 0
	FAPPCOMMAND_OEM   FAPPCOMMAND = 0x1000
)

type FILE_DISP uint32 // CreateFile dwCreationDisposition

const (
	FILE_DISP_CREATE_ALWAYS     FILE_DISP = 2
	FILE_DISP_CREATE_NEW        FILE_DISP = 1
	FILE_DISP_OPEN_ALWAYS       FILE_DISP = 4
	FILE_DISP_OPEN_EXISTING     FILE_DISP = 3
	FILE_DISP_TRUNCATE_EXISTING FILE_DISP = 5
)

type FILE_SHARE uint32 // CreateFile dwShareMode

const (
	FILE_SHARE_NONE   FILE_SHARE = 0x00000000
	FILE_SHARE_READ   FILE_SHARE = 0x00000001
	FILE_SHARE_WRITE  FILE_SHARE = 0x00000002
	FILE_SHARE_DELETE FILE_SHARE = 0x00000004
)

type FW uint32 // logfont weight

const (
	FW_DONTCARE   FW = 0
	FW_THIN       FW = 100
	FW_EXTRALIGHT FW = 200
	FW_ULTRALIGHT FW = FW_EXTRALIGHT
	FW_LIGHT      FW = 300
	FW_NORMAL     FW = 400
	FW_REGULAR    FW = 400
	FW_MEDIUM     FW = 500
	FW_SEMIBOLD   FW = 600
	FW_DEMIBOLD   FW = FW_SEMIBOLD
	FW_BOLD       FW = 700
	FW_EXTRABOLD  FW = 800
	FW_ULTRABOLD  FW = FW_EXTRABOLD
	FW_HEAVY      FW = 900
	FW_BLACK      FW = FW_HEAVY
)
