package proc

import (
	"syscall"
)

var (
	gdi32 = syscall.NewLazyDLL("gdi32.dll")

	Arc                   = gdi32.NewProc("Arc")
	ArcTo                 = gdi32.NewProc("ArcTo")
	CombineRgn            = gdi32.NewProc("CombineRgn")
	CreateCompatibleDC    = gdi32.NewProc("CreateCompatibleDC")
	CreateFontIndirect    = gdi32.NewProc("CreateFontIndirectW")
	CreateRectRgnIndirect = gdi32.NewProc("CreateRectRgnIndirect")
	CreateRoundRectRgn    = gdi32.NewProc("CreateRoundRectRgn")
	CreateSolidBrush      = gdi32.NewProc("CreateSolidBrush")
	DeleteDC              = gdi32.NewProc("DeleteDC")
	DeleteObject          = gdi32.NewProc("DeleteObject")
	Ellipse               = gdi32.NewProc("Ellipse")
	FillRect              = gdi32.NewProc("FillRect")
	FillRgn               = gdi32.NewProc("FillRgn")
	FrameRect             = gdi32.NewProc("FrameRect")
	FrameRgn              = gdi32.NewProc("FrameRgn")
	GetDeviceCaps         = gdi32.NewProc("GetDeviceCaps")
	GetPolyFillMode       = gdi32.NewProc("GetPolyFillMode")
	GetTextExtentPoint32  = gdi32.NewProc("GetTextExtentPoint32W")
	GetTextFace           = gdi32.NewProc("GetTextFaceW")
	GetTextMetrics        = gdi32.NewProc("GetTextMetricsW")
	InvertRect            = gdi32.NewProc("InvertRect")
	InvertRgn             = gdi32.NewProc("InvertRgn")
	LineTo                = gdi32.NewProc("LineTo")
	MoveToEx              = gdi32.NewProc("MoveToEx")
	PaintRgn              = gdi32.NewProc("PaintRgn")
	Pie                   = gdi32.NewProc("Pie")
	PolyDraw              = gdi32.NewProc("PolyDraw")
	Polygon               = gdi32.NewProc("Polygon")
	Polyline              = gdi32.NewProc("Polyline")
	PolylineTo            = gdi32.NewProc("PolylineTo")
	PtVisible             = gdi32.NewProc("PtVisible")
	Rectangle             = gdi32.NewProc("Rectangle")
	RestoreDC             = gdi32.NewProc("RestoreDC")
	RoundRect             = gdi32.NewProc("RoundRect")
	SaveDC                = gdi32.NewProc("SaveDC")
	SelectObject          = gdi32.NewProc("SelectObject")
	SetBkColor            = gdi32.NewProc("SetBkColor")
	SetBkMode             = gdi32.NewProc("SetBkMode")
	SetPolyFillMode       = gdi32.NewProc("SetPolyFillMode")
	SetTextAlign          = gdi32.NewProc("SetTextAlign")
	TextOut               = gdi32.NewProc("TextOutW")
)
