package consts

const CCHDEVICENAME = 32

type COLOR uint32

const (
	COLOR_3DDKSHADOW              COLOR = 21
	COLOR_3DFACE                  COLOR = 15
	COLOR_3DHIGHLIGHT             COLOR = 20
	COLOR_3DHILIGHT               COLOR = 20
	COLOR_3DLIGHT                 COLOR = 22
	COLOR_3DSHADOW                COLOR = 16
	COLOR_ACTIVEBORDER            COLOR = 10
	COLOR_ACTIVECAPTION           COLOR = 2
	COLOR_APPWORKSPACE            COLOR = 12
	COLOR_BACKGROUND              COLOR = 1
	COLOR_BTNFACE                 COLOR = 15
	COLOR_BTNHIGHLIGHT            COLOR = 20
	COLOR_BTNHILIGHT              COLOR = 20
	COLOR_BTNSHADOW               COLOR = 16
	COLOR_BTNTEXT                 COLOR = 18
	COLOR_CAPTIONTEXT             COLOR = 9
	COLOR_DESKTOP                 COLOR = 1
	COLOR_GRADIENTACTIVECAPTION   COLOR = 27
	COLOR_GRADIENTINACTIVECAPTION COLOR = 28
	COLOR_GRAYTEXT                COLOR = 17
	COLOR_HIGHLIGHT               COLOR = 13
	COLOR_HIGHLIGHTTEXT           COLOR = 14
	COLOR_HOTLIGHT                COLOR = 26
	COLOR_INACTIVEBORDER          COLOR = 11
	COLOR_INACTIVECAPTION         COLOR = 3
	COLOR_INACTIVECAPTIONTEXT     COLOR = 19
	COLOR_INFOBK                  COLOR = 24
	COLOR_INFOTEXT                COLOR = 23
	COLOR_MENU                    COLOR = 4
	COLOR_MENUHILIGHT             COLOR = 29
	COLOR_MENUBAR                 COLOR = 30
	COLOR_MENUTEXT                COLOR = 7
	COLOR_SCROLLBAR               COLOR = 0
	COLOR_WINDOW                  COLOR = 5
	COLOR_WINDOWFRAME             COLOR = 6
	COLOR_WINDOWTEXT              COLOR = 8
)

type CS uint32

const (
	CS_BYTEALIGNCLIENT CS = 0x1000
	CS_BYTEALIGNWINDOW CS = 0x2000
	CS_CLASSDC         CS = 0x0040
	CS_DBLCLKS         CS = 0x0008
	CS_DROPSHADOW      CS = 0x00020000
	CS_GLOBALCLASS     CS = 0x4000
	CS_HREDRAW         CS = 0x0002
	CS_NOCLOSE         CS = 0x0200
	CS_OWNDC           CS = 0x0020
	CS_PARENTDC        CS = 0x0080
	CS_SAVEBITS        CS = 0x0800
	CS_VREDRAW         CS = 0x0001
)

type ES WS

const (
	ES_AUTOHSCROLL ES = 0x0080
	ES_AUTOVSCROLL ES = 0x0040
	ES_CENTER      ES = 0x0001
	ES_LEFT        ES = 0x0000
	ES_LOWERCASE   ES = 0x0010
	ES_MULTILINE   ES = 0x0004
	ES_NOHIDESEL   ES = 0x0100
	ES_NUMBER      ES = 0x2000
	ES_OEMCONVERT  ES = 0x0400
	ES_PASSWORD    ES = 0x0020
	ES_READONLY    ES = 0x0800
	ES_RIGHT       ES = 0x0002
	ES_UPPERCASE   ES = 0x0008
	ES_WANTRETURN  ES = 0x1000
)

type ERROR uint32

const (
	ERROR_CLASS_ALREADY_EXISTS ERROR = 1410
)

type FW uint32

const (
	FW_DONTCARE   FW = 0
	FW_THIN       FW = 100
	FW_EXTRALIGHT FW = 200
	FW_ULTRALIGHT FW = FW_EXTRALIGHT
	FW_LIGHT      FW = 300
	FW_NORMAL     FW = 400
	FW_REGULAR    FW = 400
	FW_MEDIUM     FW = 500
	FW_SEMIBOLD   FW = 600
	FW_DEMIBOLD   FW = FW_SEMIBOLD
	FW_BOLD       FW = 700
	FW_EXTRABOLD  FW = 800
	FW_ULTRABOLD  FW = FW_EXTRABOLD
	FW_HEAVY      FW = 900
	FW_BLACK      FW = FW_HEAVY
)
