package consts

type GWLP int32

const (
	GWLP_EXSTYLE   GWLP = -20
	GWLP_HINSTANCE GWLP = -6
	GWLP_ID        GWLP = -12
	GWLP_STYLE     GWLP = -16
	GWLP_USERDATA  GWLP = -21
	GWLP_WNDPROC   GWLP = -4
)

type ID uint16

const (
	IDABORT    ID = 3
	IDCANCEL   ID = 2
	IDCONTINUE ID = 11
	IDIGNORE   ID = 5
	IDNO       ID = 7
	IDOK       ID = 1
	IDRETRY    ID = 4
	IDTRYAGAIN ID = 10
	IDYES      ID = 6
)

type IDC uintptr

const (
	IDC_APPSTARTING IDC = 32650
	IDC_ARROW       IDC = 32512
	IDC_CROSS       IDC = 32515
	IDC_HAND        IDC = 32649
	IDC_HELP        IDC = 32651
	IDC_IBEAM       IDC = 32513
	IDC_ICON        IDC = 32641
	IDC_NO          IDC = 32648
	IDC_SIZE        IDC = 32640
	IDC_SIZEALL     IDC = 32646
	IDC_SIZENESW    IDC = 32643
	IDC_SIZENS      IDC = 32645
	IDC_SIZENWSE    IDC = 32642
	IDC_SIZEWE      IDC = 32644
	IDC_UPARROW     IDC = 32516
	IDC_WAIT        IDC = 32514
)

const LF_FACESIZE = 32

type LVN WM

const (
	LVN_FIRST LVN = -100

	LVN_BEGINDRAG         LVN = LVN_FIRST - 9
	LVN_BEGINLABELEDIT    LVN = LVN_FIRST - 75
	LVN_BEGINRDRAG        LVN = LVN_FIRST - 11
	LVN_BEGINSCROLL       LVN = LVN_FIRST - 80
	LVN_COLUMNCLICK       LVN = LVN_FIRST - 8
	LVN_DELETEALLITEMS    LVN = LVN_FIRST - 4
	LVN_DELETEITEM        LVN = LVN_FIRST - 3
	LVN_ENDLABELEDIT      LVN = LVN_FIRST - 76
	LVN_ENDSCROLL         LVN = LVN_FIRST - 81
	LVN_GETDISPINFO       LVN = LVN_FIRST - 77
	LVN_GETINFOTIP        LVN = LVN_FIRST - 58
	LVN_HOTTRACK          LVN = LVN_FIRST - 21
	LVN_INCREMENTALSEARCH LVN = LVN_FIRST - 63
	LVN_ITEMACTIVATE      LVN = LVN_FIRST - 14
	LVN_ITEMCHANGED       LVN = LVN_FIRST - 1
	LVN_ITEMCHANGING      LVN = LVN_FIRST - 0
	LVN_KEYDOWN           LVN = LVN_FIRST - 55
	LVN_MARQUEEBEGIN      LVN = LVN_FIRST - 56
	LVN_ODCACHEHINT       LVN = LVN_FIRST - 13
	LVN_ODFINDITEM        LVN = LVN_FIRST - 79
	LVN_ODSTATECHANGED    LVN = LVN_FIRST - 15
	LVN_SETDISPINFO       LVN = LVN_FIRST - 78
)

type LVP uint8

const (
	LVP_LISTITEM         LVP = 1
	LVP_LISTGROUP        LVP = 2
	LVP_LISTDETAIL       LVP = 3
	LVP_LISTSORTEDDETAIL LVP = 4
	LVP_EMPTYTEXT        LVP = 5
)
