package consts

type LVCF uint32 // LVCOLUMN mask

const (
	LVCF_DEFAULTWIDTH LVCF = 0x0080
	LVCF_FMT          LVCF = 0x0001
	LVCF_IDEALWIDTH   LVCF = 0x0100
	LVCF_IMAGE        LVCF = 0x0010
	LVCF_MINWIDTH     LVCF = 0x0040
	LVCF_ORDER        LVCF = 0x0020
	LVCF_SUBITEM      LVCF = 0x0008
	LVCF_TEXT         LVCF = 0x0004
	LVCF_WIDTH        LVCF = 0x0002
)

type LVIF uint32 // LVITEM mask

const (
	LVIF_COLFMT      LVIF = 0x00010000
	LVIF_COLUMNS     LVIF = 0x00000200
	LVIF_GROUPID     LVIF = 0x00000100
	LVIF_IMAGE       LVIF = 0x00000002
	LVIF_INDENT      LVIF = 0x00000010
	LVIF_NORECOMPUTE LVIF = 0x00000800
	LVIF_PARAM       LVIF = 0x00000004
	LVIF_STATE       LVIF = 0x00000008
	LVIF_TEXT        LVIF = 0x00000001
)

type LVIS uint32 // list view item state

const (
	LVIS_FOCUSED        LVIS = 0x0001
	LVIS_SELECTED       LVIS = 0x0002
	LVIS_CUT            LVIS = 0x0004
	LVIS_DROPHILITED    LVIS = 0x0008
	LVIS_GLOW           LVIS = 0x0010
	LVIS_ACTIVATING     LVIS = 0x0020
	LVIS_OVERLAYMASK    LVIS = 0x0F00
	LVIS_STATEIMAGEMASK LVIS = 0xF000
)

type LVM WM // list view message

const (
	LVM_FIRST LVM = 0x1000

	LVM_GETBKCOLOR               LVM = LVM_FIRST + 0
	LVM_SETBKCOLOR               LVM = LVM_FIRST + 1
	LVM_GETIMAGELIST             LVM = LVM_FIRST + 2
	LVM_SETIMAGELIST             LVM = LVM_FIRST + 3
	LVM_GETITEMCOUNT             LVM = LVM_FIRST + 4
	LVM_DELETEITEM               LVM = LVM_FIRST + 8
	LVM_DELETEALLITEMS           LVM = LVM_FIRST + 9
	LVM_GETCOLUMNWIDTH           LVM = LVM_FIRST + 29
	LVM_SETCOLUMNWIDTH           LVM = LVM_FIRST + 30
	LVM_GETHEADER                LVM = LVM_FIRST + 31
	LVM_CREATEDRAGIMAGE          LVM = LVM_FIRST + 33
	LVM_GETVIEWRECT              LVM = LVM_FIRST + 34
	LVM_GETTEXTCOLOR             LVM = LVM_FIRST + 35
	LVM_SETTEXTCOLOR             LVM = LVM_FIRST + 36
	LVM_GETTEXTBKCOLOR           LVM = LVM_FIRST + 37
	LVM_SETTEXTBKCOLOR           LVM = LVM_FIRST + 38
	LVM_GETTOPINDEX              LVM = LVM_FIRST + 39
	LVM_GETCOUNTPERPAGE          LVM = LVM_FIRST + 40
	LVM_GETORIGIN                LVM = LVM_FIRST + 41
	LVM_UPDATE                   LVM = LVM_FIRST + 42
	LVM_SETITEMSTATE             LVM = LVM_FIRST + 43
	LVM_GETITEMSTATE             LVM = LVM_FIRST + 44
	LVM_SORTITEMS                LVM = LVM_FIRST + 48
	LVM_SETITEMPOSITION32        LVM = LVM_FIRST + 49
	LVM_GETSELECTEDCOUNT         LVM = LVM_FIRST + 50
	LVM_SETICONSPACING           LVM = LVM_FIRST + 53
	LVM_SETEXTENDEDLISTVIEWSTYLE LVM = LVM_FIRST + 54
	LVM_GETEXTENDEDLISTVIEWSTYLE LVM = LVM_FIRST + 55
	LVM_APPROXIMATEVIEWRECT      LVM = LVM_FIRST + 64
	LVM_SETTOOLTIPS              LVM = LVM_FIRST + 74
	LVM_GETITEM                  LVM = LVM_FIRST + 75
	LVM_SETITEM                  LVM = LVM_FIRST + 76
	LVM_INSERTITEM               LVM = LVM_FIRST + 77
	LVM_GETTOOLTIPS              LVM = LVM_FIRST + 78
	LVM_GETCOLUMN                LVM = LVM_FIRST + 95
	LVM_SETCOLUMN                LVM = LVM_FIRST + 96
	LVM_INSERTCOLUMN             LVM = LVM_FIRST + 97
	LVM_GETITEMTEXT              LVM = LVM_FIRST + 115
	LVM_SETITEMTEXT              LVM = LVM_FIRST + 116
	LVM_GETISEARCHSTRING         LVM = LVM_FIRST + 117
	LVM_SETBKIMAGE               LVM = LVM_FIRST + 138
	LVM_GETBKIMAGE               LVM = LVM_FIRST + 139
	LVM_SETVIEW                  LVM = LVM_FIRST + 142
	LVM_GETVIEW                  LVM = LVM_FIRST + 143
	LVM_HASGROUP                 LVM = LVM_FIRST + 161
	LVM_ISGROUPVIEWENABLED       LVM = LVM_FIRST + 175
	LVM_ISITEMVISIBLE            LVM = LVM_FIRST + 182
	LVM_GETEMPTYTEXT             LVM = LVM_FIRST + 204
)

type LVN WM // list view notification

const (
	LVN_FIRST LVN = -100

	LVN_BEGINDRAG         LVN = LVN_FIRST - 9
	LVN_BEGINLABELEDIT    LVN = LVN_FIRST - 75
	LVN_BEGINRDRAG        LVN = LVN_FIRST - 11
	LVN_BEGINSCROLL       LVN = LVN_FIRST - 80
	LVN_COLUMNCLICK       LVN = LVN_FIRST - 8
	LVN_DELETEALLITEMS    LVN = LVN_FIRST - 4
	LVN_DELETEITEM        LVN = LVN_FIRST - 3
	LVN_ENDLABELEDIT      LVN = LVN_FIRST - 76
	LVN_ENDSCROLL         LVN = LVN_FIRST - 81
	LVN_GETDISPINFO       LVN = LVN_FIRST - 77
	LVN_GETINFOTIP        LVN = LVN_FIRST - 58
	LVN_HOTTRACK          LVN = LVN_FIRST - 21
	LVN_INCREMENTALSEARCH LVN = LVN_FIRST - 63
	LVN_ITEMACTIVATE      LVN = LVN_FIRST - 14
	LVN_ITEMCHANGED       LVN = LVN_FIRST - 1
	LVN_ITEMCHANGING      LVN = LVN_FIRST - 0
	LVN_KEYDOWN           LVN = LVN_FIRST - 55
	LVN_MARQUEEBEGIN      LVN = LVN_FIRST - 56
	LVN_ODCACHEHINT       LVN = LVN_FIRST - 13
	LVN_ODFINDITEM        LVN = LVN_FIRST - 79
	LVN_ODSTATECHANGED    LVN = LVN_FIRST - 15
	LVN_SETDISPINFO       LVN = LVN_FIRST - 78
)

type LVP uint8 // DrawThemeBackground

const (
	LVP_LISTITEM         LVP = 1
	LVP_LISTGROUP        LVP = 2
	LVP_LISTDETAIL       LVP = 3
	LVP_LISTSORTEDDETAIL LVP = 4
	LVP_EMPTYTEXT        LVP = 5
)

type LVS WS // list view style

const (
	LVS_ALIGNLEFT       LVS = 0x0800
	LVS_ALIGNMASK       LVS = 0x0c00
	LVS_ALIGNTOP        LVS = 0x0000
	LVS_AUTOARRANGE     LVS = 0x0100
	LVS_EDITLABELS      LVS = 0x0200
	LVS_ICON            LVS = 0x0000
	LVS_LIST            LVS = 0x0003
	LVS_NOCOLUMNHEADER  LVS = 0x4000
	LVS_NOLABELWRAP     LVS = 0x0080
	LVS_NOSCROLL        LVS = 0x2000
	LVS_NOSORTHEADER    LVS = 0x8000
	LVS_OWNERDATA       LVS = 0x1000
	LVS_OWNERDRAWFIXED  LVS = 0x0400
	LVS_REPORT          LVS = 0x0001
	LVS_SHAREIMAGELISTS LVS = 0x0040
	LVS_SHOWSELALWAYS   LVS = 0x0008
	LVS_SINGLESEL       LVS = 0x0004
	LVS_SMALLICON       LVS = 0x0002
	LVS_SORTASCENDING   LVS = 0x0010
	LVS_SORTDESCENDING  LVS = 0x0020
	LVS_TYPEMASK        LVS = 0x0003
	LVS_TYPESTYLEMASK   LVS = 0xfc00
)

type LVS_EX WS_EX // list view extended style

const (
	LVS_EX_AUTOAUTOARRANGE       LVS_EX = 0x01000000
	LVS_EX_AUTOCHECKSELECT       LVS_EX = 0x08000000
	LVS_EX_AUTOSIZECOLUMNS       LVS_EX = 0x10000000
	LVS_EX_BORDERSELECT          LVS_EX = 0x00008000
	LVS_EX_CHECKBOXES            LVS_EX = 0x00000004
	LVS_EX_COLUMNOVERFLOW        LVS_EX = 0x80000000
	LVS_EX_COLUMNSNAPPOINTS      LVS_EX = 0x40000000
	LVS_EX_DOUBLEBUFFER          LVS_EX = 0x00010000
	LVS_EX_FLATSB                LVS_EX = 0x00000100
	LVS_EX_FULLROWSELECT         LVS_EX = 0x00000020
	LVS_EX_GRIDLINES             LVS_EX = 0x00000001
	LVS_EX_HEADERDRAGDROP        LVS_EX = 0x00000010
	LVS_EX_HEADERINALLVIEWS      LVS_EX = 0x02000000
	LVS_EX_HIDELABELS            LVS_EX = 0x00020000
	LVS_EX_INFOTIP               LVS_EX = 0x00000400
	LVS_EX_JUSTIFYCOLUMNS        LVS_EX = 0x00200000
	LVS_EX_LABELTIP              LVS_EX = 0x00004000
	LVS_EX_MULTIWORKAREAS        LVS_EX = 0x00002000
	LVS_EX_ONECLICKACTIVATE      LVS_EX = 0x00000040
	LVS_EX_REGIONAL              LVS_EX = 0x00000200
	LVS_EX_SIMPLESELECT          LVS_EX = 0x00100000
	LVS_EX_SINGLEROW             LVS_EX = 0x00040000
	LVS_EX_SNAPTOGRID            LVS_EX = 0x00080000
	LVS_EX_SUBITEMIMAGES         LVS_EX = 0x00000002
	LVS_EX_TRACKSELECT           LVS_EX = 0x00000008
	LVS_EX_TRANSPARENTBKGND      LVS_EX = 0x00400000
	LVS_EX_TRANSPARENTSHADOWTEXT LVS_EX = 0x00800000
	LVS_EX_TWOCLICKACTIVATE      LVS_EX = 0x00000080
	LVS_EX_UNDERLINECOLD         LVS_EX = 0x00001000
	LVS_EX_UNDERLINEHOT          LVS_EX = 0x00000800
)
