package consts

const LF_FACESIZE = 32

type LVN WM

const (
	LVN_FIRST LVN = -100

	LVN_BEGINDRAG         LVN = LVN_FIRST - 9
	LVN_BEGINLABELEDIT    LVN = LVN_FIRST - 75
	LVN_BEGINRDRAG        LVN = LVN_FIRST - 11
	LVN_BEGINSCROLL       LVN = LVN_FIRST - 80
	LVN_COLUMNCLICK       LVN = LVN_FIRST - 8
	LVN_DELETEALLITEMS    LVN = LVN_FIRST - 4
	LVN_DELETEITEM        LVN = LVN_FIRST - 3
	LVN_ENDLABELEDIT      LVN = LVN_FIRST - 76
	LVN_ENDSCROLL         LVN = LVN_FIRST - 81
	LVN_GETDISPINFO       LVN = LVN_FIRST - 77
	LVN_GETINFOTIP        LVN = LVN_FIRST - 58
	LVN_HOTTRACK          LVN = LVN_FIRST - 21
	LVN_INCREMENTALSEARCH LVN = LVN_FIRST - 63
	LVN_ITEMACTIVATE      LVN = LVN_FIRST - 14
	LVN_ITEMCHANGED       LVN = LVN_FIRST - 1
	LVN_ITEMCHANGING      LVN = LVN_FIRST - 0
	LVN_KEYDOWN           LVN = LVN_FIRST - 55
	LVN_MARQUEEBEGIN      LVN = LVN_FIRST - 56
	LVN_ODCACHEHINT       LVN = LVN_FIRST - 13
	LVN_ODFINDITEM        LVN = LVN_FIRST - 79
	LVN_ODSTATECHANGED    LVN = LVN_FIRST - 15
	LVN_SETDISPINFO       LVN = LVN_FIRST - 78
)

type LVP uint8

const (
	LVP_LISTITEM         LVP = 1
	LVP_LISTGROUP        LVP = 2
	LVP_LISTDETAIL       LVP = 3
	LVP_LISTSORTEDDETAIL LVP = 4
	LVP_EMPTYTEXT        LVP = 5
)
