package consts

type SIZE int32

const (
	SIZE_MAXHIDE   SIZE = 4
	SIZE_MAXIMIZED SIZE = 2
	SIZE_MAXSHOW   SIZE = 3
	SIZE_MINIMIZED SIZE = 1
	SIZE_RESTORED  SIZE = 0
)

type SM int32

const (
	SM_CMONITORS SM = 80
	SM_CXSCREEN  SM = 0
	SM_CYSCREEN  SM = 1
)

type SW int32

const (
	SW_FORCEMINIMIZE   SW = 11
	SW_HIDE            SW = 0
	SW_MAXIMIZE        SW = 3
	SW_MINIMIZE        SW = 6
	SW_RESTORE         SW = 9
	SW_SHOW            SW = 5
	SW_SHOWDEFAULT     SW = 10
	SW_SHOWMAXIMIZED   SW = 3
	SW_SHOWMINIMIZED   SW = 2
	SW_SHOWMINNOACTIVE SW = 7
	SW_SHOWNA          SW = 8
	SW_SHOWNOACTIVATE  SW = 4
	SW_SHOWNORMAL      SW = 1
)

type VER uint32
type VERCOND uint8

const (
	VER_BUILDNUMBER      VER = 0x0000004
	VER_MAJORVERSION     VER = 0x0000002
	VER_MINORVERSION     VER = 0x0000001
	VER_PLATFORMID       VER = 0x0000008
	VER_PRODUCT_TYPE     VER = 0x0000080
	VER_SERVICEPACKMAJOR VER = 0x0000020
	VER_SERVICEPACKMINOR VER = 0x0000010
	VER_SUITENAME        VER = 0x0000040

	VER_EQUAL         VERCOND = 1
	VER_GREATER       VERCOND = 2
	VER_GREATER_EQUAL VERCOND = 3
	VER_LESS          VERCOND = 4
	VER_LESS_EQUAL    VERCOND = 5

	VER_AND VERCOND = 6
	VER_OR  VERCOND = 7
)
