package proc

import (
	"syscall"
)

var (
	dllUser32 = syscall.NewLazyDLL("user32.dll")

	ClientToScreen          = dllUser32.NewProc("ClientToScreen")
	CopyAcceleratorTable    = dllUser32.NewProc("CopyAcceleratorTableW")
	CreateAcceleratorTable  = dllUser32.NewProc("CreateAcceleratorTableW")
	CreateWindowEx          = dllUser32.NewProc("CreateWindowExW")
	DefWindowProc           = dllUser32.NewProc("DefWindowProcW")
	DestroyAcceleratorTable = dllUser32.NewProc("DestroyAcceleratorTable")
	DestroyWindow           = dllUser32.NewProc("DestroyWindow")
	DispatchMessage         = dllUser32.NewProc("DispatchMessageW")
	EnableWindow            = dllUser32.NewProc("EnableWindow")
	EnumChildWindows        = dllUser32.NewProc("EnumChildWindows")
	EnumDisplayMonitors     = dllUser32.NewProc("EnumDisplayMonitors")
	GetAncestor             = dllUser32.NewProc("GetAncestor")
	GetClassInfo            = dllUser32.NewProc("GetClassInfoW")
	GetForegroundWindow     = dllUser32.NewProc("GetForegroundWindow")
	GetMessage              = dllUser32.NewProc("GetMessageW")
	GetMonitorInfo          = dllUser32.NewProc("GetMonitorInfoW")
	GetParent               = dllUser32.NewProc("GetParent")
	GetSystemMetrics        = dllUser32.NewProc("GetSystemMetrics")
	GetWindowDC             = dllUser32.NewProc("GetWindowDC")
	GetWindowLongPtr        = dllUser32.NewProc("SetWindowLongPtrW")
	GetWindowRect           = dllUser32.NewProc("GetWindowRect")
	GetWindowText           = dllUser32.NewProc("GetWindowTextW")
	GetWindowTextLength     = dllUser32.NewProc("GetWindowTextLengthW")
	InvalidateRect          = dllUser32.NewProc("InvalidateRect")
	IsDialogMessage         = dllUser32.NewProc("IsDialogMessageW")
	IsWindowEnabled         = dllUser32.NewProc("IsWindowEnabled")
	LoadCursor              = dllUser32.NewProc("LoadCursorW")
	MessageBox              = dllUser32.NewProc("MessageBoxW")
	PostQuitMessage         = dllUser32.NewProc("PostQuitMessage")
	RegisterClassEx         = dllUser32.NewProc("RegisterClassExW")
	ReleaseDC               = dllUser32.NewProc("ReleaseDC")
	ScreenToClient          = dllUser32.NewProc("ScreenToClient")
	SendMessage             = dllUser32.NewProc("SendMessageW")
	SetFocus                = dllUser32.NewProc("SetFocus")
	SetRect                 = dllUser32.NewProc("SetRect")
	SetWindowLongPtr        = dllUser32.NewProc("SetWindowLongPtrW")
	SetWindowText           = dllUser32.NewProc("SetWindowTextW")
	ShowWindow              = dllUser32.NewProc("ShowWindow")
	SystemParametersInfo    = dllUser32.NewProc("SystemParametersInfoW")
	TranslateAccelerator    = dllUser32.NewProc("TranslateAcceleratorW")
	TranslateMessage        = dllUser32.NewProc("TranslateMessage")
	UpdateWindow            = dllUser32.NewProc("UpdateWindow")
)
